name: Deploy Flask to Azure

on:
  push:
    branches:
      - flask

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp up \
          --name flask-api-ua2025 \
          --resource-group flask-rg \
          --plan flask-api-plan \
          --runtime "PYTHON|3.11" \
          --sku F1 \
          --overwrite

